import { readFile, readdir, mkdir, cp, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { productDetail, digitalCatalog } from './product-pages.mjs';
import { slides, contactPage, thankYou } from './experience.mjs';

const root = path.resolve(import.meta.dirname, '..');
const origin = (process.env.SITE_URL || process.env.URL || 'https://artink-studio-example.netlify.app').replace(/\/$/, '');
const out = path.join(root, 'dist');
const files = (await readdir(path.join(root, 'content/products'))).filter(f => f.endsWith('.json'));
const products = (await Promise.all(files.map(async f => JSON.parse(await readFile(path.join(root, 'content/products', f), 'utf8'))))).filter(p => p.active !== false);
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const categories = ['tshirts','hoodies','mugs','magnets','caps','invitations','gifts'];
const seen = new Set();
for (const p of products) {
  if (!slugPattern.test(p.slug) || seen.has(p.slug)) throw new Error(`Invalid or duplicate slug: ${p.slug}`);
  seen.add(p.slug);
  if (!categories.includes(p.category)) throw new Error(`Invalid category for ${p.slug}`);
  for (const lang of ['en','mk','sq']) if (!p[`name_${lang}`] || !p[`short_${lang}`] || !p[`description_${lang}`]) throw new Error(`Translation ${lang} missing for ${p.slug}`);
  if (!Array.isArray(p.images) || !p.images.length) throw new Error(`Image missing for ${p.slug}`);
  const colors = Array.isArray(p.colors) ? p.colors : [];
  const sizes = Array.isArray(p.sizes) ? p.sizes : [];
  const stock = Array.isArray(p.stock) ? p.stock : [];
  for (const color of colors) if (!color.name || !/^#[0-9a-fA-F]{6}$/.test(color.hex)) throw new Error(`Invalid colour for ${p.slug}`);
  if (new Set(colors.map(c => c.name.toLocaleLowerCase())).size !== colors.length) throw new Error(`Duplicate colour for ${p.slug}`);
  if (new Set(sizes).size !== sizes.length) throw new Error(`Duplicate size for ${p.slug}`);
  const usedVariants = new Set();
  for (const item of stock) {
    const color = String(item.color || '').trim();
    const size = String(item.size || '').trim();
    if (colors.length && !colors.some(c => c.name.toLocaleLowerCase() === color.toLocaleLowerCase())) throw new Error(`Unknown stock colour for ${p.slug}: ${color}`);
    if (sizes.length && !sizes.includes(size)) throw new Error(`Unknown stock size for ${p.slug}: ${size}`);
    if (!Number.isInteger(Number(item.quantity)) || Number(item.quantity) < 0) throw new Error(`Invalid stock quantity for ${p.slug}`);
    const key = `${color.toLocaleLowerCase()}:${size.toLocaleUpperCase()}`;
    if (usedVariants.has(key)) throw new Error(`Duplicate stock variant for ${p.slug}: ${key}`);
    usedVariants.add(key);
  }
}
const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t = {
  en: {navCatalog:'Catalogue',navAbout:'The studio',navContact:'Contact',heroEyebrow:'DESIGN · PRINT · ENGRAVE',heroTitle:'Made to mean more.',heroText:'Personalised apparel, gifts and printed pieces for the people and moments that matter.',browse:'Explore catalogue',talk:'Tell us your idea',strip:'Your idea, your details, our craft.',title:'Find your next favourite thing.',catalogText:'Browse possibilities. Every piece can be tailored to your brief.',search:'Search products…',all:'All',noResults:'No products match your search.',view:'View details',featured:'Selected work',aboutKicker:'ARTINK STUDIO / SKOPJE',aboutTitle:'Thoughtful details, made tangible.',aboutText:'From a single personalised mug to clothing for a whole team, we help turn your artwork into something people can hold, wear or share. Tell us what you have in mind and we will discuss material, technique and quantity.',contactTitle:'Let’s make it yours.',contactText:'Send us your idea, quantity and deadline. We will get back to you with options and a quote.',email:'Email us',whatsapp:'WhatsApp',instagram:'Instagram',call:'Call',quote:'Request a quote by email',options:'Materials and options',availability:'Model, colour and availability are confirmed before production.',back:'Back to catalogue',privacy:'Privacy policy',privacyIntro:'We use essential local storage to remember your privacy notice choice. No analytics or advertising cookies are installed in this version.',accept:'Got it',photoNote:'Images are visual examples. Final models and finishes are confirmed in your quote.',copyright:'ArtInk Studio · Design • Print • Engrave',subject:'Quote request',body:'Hello ArtInk Studio,\n\nI would like a quote for:\nProduct: ',qty:'Quantity: \nPreferred colour / size: \nPrint or personalisation details: \nDeadline: \n\nMy name and phone number: ',language:'Language',previous:'Previous image',next:'Next image'},
  mk: {navCatalog:'Каталог',navAbout:'За студиото',navContact:'Контакт',heroEyebrow:'ДИЗАЈН · ПЕЧАТ · ГРАВИРАЊЕ',heroTitle:'Создадено со значење.',heroText:'Персонализирана облека, подароци и печатени производи за важните луѓе и моменти.',browse:'Истражи каталог',talk:'Кажи ни ја идејата',strip:'Твоја идеја, твои детали, наша изработка.',title:'Пронајди го вистинскиот производ.',catalogText:'Разгледај можности. Секој производ го приспособуваме на твојата идеја.',search:'Пребарај производи…',all:'Сите',noResults:'Нема производи за ова пребарување.',view:'Погледни детали',featured:'Избрани производи',aboutKicker:'ARTINK STUDIO / СКОПЈЕ',aboutTitle:'Деталите стануваат нешто вистинско.',aboutText:'Од една персонализирана чаша до облека за цел тим, го претвораме твојот дизајн во производ што се носи, подарува и памети. Пиши ни за материјал, техника и количина.',contactTitle:'Да го направиме по твоја мерка.',contactText:'Испрати идеја, количина и рок. Ќе ти одговориме со предлог и понуда.',email:'Е-пошта',whatsapp:'WhatsApp',instagram:'Instagram',call:'Јави се',quote:'Побарај понуда по е-пошта',options:'Материјали и опции',availability:'Моделот, бојата и достапноста се потврдуваат пред изработка.',back:'Назад кон каталог',privacy:'Политика за приватност',privacyIntro:'Користиме само неопходно локално складирање за да го запомниме изборот за известувањето. Оваа верзија нема аналитички или рекламни колачиња.',accept:'Во ред',photoNote:'Сликите се визуелни примери. Точниот модел и изработка се потврдуваат во понудата.',copyright:'ArtInk Studio · Дизајн • Печат • Гравирање',subject:'Барање понуда',body:'Здраво ArtInk Studio,\n\nСакам понуда за:\nПроизвод: ',qty:'Количина: \nПосакувана боја / големина: \nДетали за печат или персонализација: \nРок: \n\nМое име и телефон: ',language:'Јазик',previous:'Претходна слика',next:'Следна слика'},
  sq: {navCatalog:'Katalogu',navAbout:'Rreth studios',navContact:'Kontakt',heroEyebrow:'DIZAJN · PRINTIM · GRAVIM',heroTitle:'Krijuar me kuptim.',heroText:'Veshje, dhurata dhe produkte të shtypura të personalizuara për njerëzit dhe momentet që kanë rëndësi.',browse:'Shiko katalogun',talk:'Na trego idenë',strip:'Ideja jote, detajet e tua, puna jonë.',title:'Gjej produktin e duhur.',catalogText:'Shiko mundësitë. Çdo produkt mund të përshtatet sipas idesë tënde.',search:'Kërko produkte…',all:'Të gjitha',noResults:'Nuk u gjet asnjë produkt.',view:'Shiko detajet',featured:'Produkte të zgjedhura',aboutKicker:'ARTINK STUDIO / SHKUP',aboutTitle:'Detajet marrin formë.',aboutText:'Nga një filxhan i personalizuar te veshjet për gjithë ekipin, e kthejmë dizajnin tënd në një produkt që mund të vishet, dhurohet dhe mbahet mend. Na shkruaj për materialin, teknikën dhe sasinë.',contactTitle:'Ta krijojmë sipas teje.',contactText:'Dërgo idenë, sasinë dhe afatin. Do të përgjigjemi me mundësi dhe ofertë.',email:'Email',whatsapp:'WhatsApp',instagram:'Instagram',call:'Na telefono',quote:'Kërko ofertë me email',options:'Materialet dhe opsionet',availability:'Modeli, ngjyra dhe disponueshmëria konfirmohen para prodhimit.',back:'Kthehu te katalogu',privacy:'Politika e privatësisë',privacyIntro:'Përdorim vetëm ruajtje lokale të nevojshme për të mbajtur mend zgjedhjen tënde për njoftimin. Kjo faqe nuk vendos cookies për analiza ose reklama.',accept:'Në rregull',photoNote:'Fotot janë shembuj vizualë. Modeli dhe përfundimi konfirmohen në ofertë.',copyright:'ArtInk Studio · Dizajn • Printim • Gravim',subject:'Kërkesë për ofertë',body:'Përshëndetje ArtInk Studio,\n\nDëshiroj një ofertë për:\nProduktin: ',qty:'Sasia: \nNgjyra / madhësia: \nDetajet e printimit ose personalizimit: \nAfati: \n\nEmri dhe telefoni im: ',language:'Gjuha',previous:'Foto e mëparshme',next:'Fotoja tjetër'}
};
Object.assign(t.en, {navProducts:'Products',navCatalog:'Catalogue',back:'Back to products',browse:'Explore products',colors:'Available colours',sizes:'Available sizes',code:'Code',model:'Model',brand:'Brand',material:'Material',weight:'Weight',packaging:'Packaging',collection:'Collection',gallery:'Product gallery',image:'Image',inStock:'In stock',outOfStock:'Currently unavailable',askStock:'Ask us to confirm availability',selectedColor:'Selected colour',selectedSize:'Selected size',discoverMore:'MORE TO EXPLORE',related:'Similar products',viewGroup:'Explore this group',lookbookTitle:'The ArtInk collection.',lookbookIntro:'A curated way to explore what we can make together.',browseChapters:'Browse chapters',chapters:'Chapters',exploreCollection:'Explore by category.',items:'products',catalogCover:'ArtInk catalogue cover',openPdf:'Open PDF',pdfCatalog:'PDF catalogue'});
Object.assign(t.mk, {navProducts:'Продукти',navCatalog:'Каталог',back:'Назад кон продукти',browse:'Разгледај продукти',colors:'Достапни бои',sizes:'Достапни големини',code:'Шифра',model:'Модел',brand:'Марка',material:'Материјал',weight:'Граматура',packaging:'Пакување',collection:'Колекција',gallery:'Галерија на производот',image:'Слика',inStock:'На залиха',outOfStock:'Моментално нема на залиха',askStock:'Побарај потврда за достапност',selectedColor:'Избрана боја',selectedSize:'Избрана големина',discoverMore:'РАЗГЛЕДАЈ ПОВЕЌЕ',related:'Слични производи',viewGroup:'Разгледај ја групата',lookbookTitle:'Колекцијата на ArtInk.',lookbookIntro:'Визуелен преглед на производите што можеме да ги изработиме.',browseChapters:'Разгледај групи',chapters:'Групи',exploreCollection:'Истражи по група.',items:'производи',catalogCover:'Насловна слика за каталогот',openPdf:'Отвори PDF',pdfCatalog:'PDF каталог'});
Object.assign(t.sq, {navProducts:'Produkte',navCatalog:'Katalogu',back:'Kthehu te produktet',browse:'Shiko produktet',colors:'Ngjyrat e disponueshme',sizes:'Madhësitë e disponueshme',code:'Kodi',model:'Modeli',brand:'Marka',material:'Materiali',weight:'Pesha',packaging:'Paketimi',collection:'Koleksioni',gallery:'Galeria e produktit',image:'Foto',inStock:'Në stok',outOfStock:'Për momentin nuk ka stok',askStock:'Kërko konfirmim për stokun',selectedColor:'Ngjyra e zgjedhur',selectedSize:'Madhësia e zgjedhur',discoverMore:'SHIKO MË SHUMË',related:'Produkte të ngjashme',viewGroup:'Shiko këtë kategori',lookbookTitle:'Koleksioni ArtInk.',lookbookIntro:'Një pasqyrë vizuale e produkteve që mund të krijojmë.',browseChapters:'Shiko kategoritë',chapters:'Kategoritë',exploreCollection:'Shiko sipas kategorisë.',items:'produkte',catalogCover:'Kopertina e katalogut',openPdf:'Hap PDF',pdfCatalog:'Katalogu PDF'});
Object.assign(t.en, {slidesLabel:'Featured ideas',slideLabel:'Show slide',previousSlide:'Previous slide',nextSlide:'Next slide',slideClothesTag:'PERSONALISED APPAREL',slideClothesTitle:'Wear your idea.',slideClothesText:'T-shirts and hoodies designed for your team, event or brand.',slideMomentsTag:'MOMENTS & GIFTS',slideMomentsTitle:'Little things. Lasting memories.',slideMomentsText:'Invitations, mugs and keepsakes with your own story.',inquiryTag:'YOUR IDEA',inquiryTitle:'Send us your brief.',inquiryHint:'We’ll reply to your email with options and a quote.',yourName:'Your name',yourEmail:'Email address',yourPhone:'Phone (optional)',requestedQuantity:'Quantity',productName:'Product / model',colour:'Preferred colour',size:'Preferred size',message:'Your idea, print details and deadline',messagePlaceholder:'Tell us what you would like to personalise, how many you need and when…',formPrivacy:'We use your details to reply to this inquiry.',sendInquiry:'Send inquiry',otherContact:'OTHER WAYS TO REACH US',otherContactTitle:'Prefer a conversation?',otherContactText:'Write directly or send a quick WhatsApp message.',localFormNote:'This form sends messages after the site is deployed to Netlify. For local testing, use the email or WhatsApp link.',sentTitle:'Thank you for reaching out.',sentText:'Your inquiry was submitted. We’ll get back to you by email as soon as we can.',quantityNote:'The final price depends on quantity and personalisation.',quantityLabel:'Quantity',quoteForm:'Send inquiry',quoteEmail:'Open email',quoteWhatsapp:'Message on WhatsApp'});
Object.assign(t.mk, {slidesLabel:'Истакнати идеи',slideLabel:'Прикажи слајд',previousSlide:'Претходен слајд',nextSlide:'Следен слајд',slideClothesTag:'ПЕРСОНАЛИЗИРАНА ОБЛЕКА',slideClothesTitle:'Носи ја својата идеја.',slideClothesText:'Маички и дуксери за твојот тим, настан или бренд.',slideMomentsTag:'МOМЕНТИ И ПОДАРОЦИ',slideMomentsTitle:'Мали детали. Големи спомени.',slideMomentsText:'Покани, чаши и подароци со твојата приказна.',inquiryTag:'ТВОЈА ИДЕЈА',inquiryTitle:'Испрати ни ја идејата.',inquiryHint:'Ќе ти одговориме по е-пошта со можности и понуда.',yourName:'Име',yourEmail:'Е-пошта',yourPhone:'Телефон (незадолжително)',requestedQuantity:'Количина',productName:'Производ / модел',colour:'Посакувана боја',size:'Посакувана големина',message:'Идеја, детали за печатење и рок',messagePlaceholder:'Пиши што сакаш да персонализираш, колку парчиња ти требаат и кога…',formPrivacy:'Податоците ги користиме за да одговориме на ова барање.',sendInquiry:'Испрати барање',otherContact:'ДРУГ НАЧИН ЗА КОНТАКТ',otherContactTitle:'Сакаш да разговараме?',otherContactText:'Пиши директно или испрати порака на WhatsApp.',localFormNote:'Формата испраќа пораки по објавување на Netlify. При локално тестирање користи го линкот за е-пошта или WhatsApp.',sentTitle:'Ти благодариме за пораката.',sentText:'Барањето е испратено. Ќе ти одговориме по е-пошта што е можно поскоро.',quantityNote:'Крајната цена зависи од количината и персонализацијата.',quantityLabel:'Количина',quoteForm:'Испрати барање',quoteEmail:'Отвори е-пошта',quoteWhatsapp:'Пиши на WhatsApp'});
Object.assign(t.sq, {slidesLabel:'Idetë e veçuara',slideLabel:'Shfaq slajdin',previousSlide:'Slajdi i mëparshëm',nextSlide:'Slajdi tjetër',slideClothesTag:'VESHJE TË PERSONALIZUARA',slideClothesTitle:'Vish idenë tënde.',slideClothesText:'Bluza dhe hoodie për ekipin, eventin ose markën tënde.',slideMomentsTag:'MOMENTE DHE DHURATA',slideMomentsTitle:'Detaje të vogla. Kujtime të mëdha.',slideMomentsText:'Ftesa, filxhanë dhe dhurata me historinë tënde.',inquiryTag:'IDEJA JOTE',inquiryTitle:'Na dërgo idenë tënde.',inquiryHint:'Do të përgjigjemi me email me mundësi dhe ofertë.',yourName:'Emri',yourEmail:'Adresa e emailit',yourPhone:'Telefoni (opsional)',requestedQuantity:'Sasia',productName:'Produkti / modeli',colour:'Ngjyra e preferuar',size:'Madhësia e preferuar',message:'Ideja, detajet e printimit dhe afati',messagePlaceholder:'Na trego çfarë dëshiron të personalizosh, sa të duhen dhe kur…',formPrivacy:'Përdorim të dhënat e tua për t’iu përgjigjur kësaj kërkese.',sendInquiry:'Dërgo kërkesën',otherContact:'MËNYRA TË TJERA KONTAKTI',otherContactTitle:'Preferon të bisedojmë?',otherContactText:'Na shkruaj drejtpërdrejt ose përmes WhatsApp.',localFormNote:'Formulari dërgon mesazhe pasi faqja të publikohet në Netlify. Gjatë provës lokale përdor emailin ose WhatsApp.',sentTitle:'Faleminderit për mesazhin.',sentText:'Kërkesa u dërgua. Do të të përgjigjemi me email sa më shpejt.',quantityNote:'Çmimi përfundimtar varet nga sasia dhe personalizimi.',quantityLabel:'Sasia',quoteForm:'Dërgo kërkesë',quoteEmail:'Hap emailin',quoteWhatsapp:'Shkruaj në WhatsApp'});
const cat = {en:['T-shirts','Hoodies','Mugs','Magnets','Caps','Invitations','Gifts'],mk:['Маички','Дуксери','Чаши','Магнети','Капи','Покани','Подароци'],sq:['Bluza','Hoodie','Filxhanë','Magnetë','Kapele','Ftesa','Dhurata']};
const base = lang => lang === 'en' ? '' : `/${lang}`;
const url = (lang, suffix = '') => `${base(lang)}${suffix || '/'}`;
const activePath = active => active === 'products' ? '/products/' : active === 'lookbook' ? '/catalog/' : active?.startsWith('product:') ? `/product/${active.slice(8)}/` : active === 'privacy' ? '/privacy/' : active === 'contact' ? '/contact/' : active === 'sent' ? '/contact/sent/' : '';
const nav = (lang, active) => `<header class="site-header"><div class="container-fluid page-width d-flex align-items-center justify-content-between gap-3"><a class="brand" href="${url(lang)}" aria-label="ArtInk Studio home"><span class="logo-slot" aria-hidden="true"></span><span>ARTINK <small>STUDIO</small></span></a><nav class="desktop-nav" aria-label="Main"><a class="${active==='products'?'is-active':''}" href="${url(lang,'/products/')}">${t[lang].navProducts}</a><a class="${active==='lookbook'?'is-active':''}" href="${url(lang,'/catalog/')}">${t[lang].navCatalog}</a><a href="${url(lang)}#about">${t[lang].navAbout}</a><a class="${active==='contact'?'is-active':''}" href="${url(lang,'/contact/')}">${t[lang].navContact}</a></nav><div class="header-actions"><div class="language-switch" aria-label="${t[lang].language}">${['en','mk','sq'].map(l=>`<a href="${url(l,activePath(active))}" ${lang===l?'aria-current="page"':''}>${l==='sq'?'AL':l.toUpperCase()}</a>`).join('')}</div><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu">☰</button></div></div><nav id="mobile-menu" class="mobile-nav" aria-label="Mobile"><a href="${url(lang,'/products/')}">${t[lang].navProducts}</a><a href="${url(lang,'/catalog/')}">${t[lang].navCatalog}</a><a href="${url(lang)}#about">${t[lang].navAbout}</a><a href="${url(lang,'/contact/')}">${t[lang].navContact}</a></nav></header>`;
const footer = lang => `<footer class="footer"><div class="container-fluid page-width footer-grid"><div><a class="brand" href="${url(lang)}"><span class="logo-slot" aria-hidden="true"></span><span>ARTINK <small>STUDIO</small></span></a><p>${t[lang].copyright}</p></div><div class="footer-links"><a href="mailto:artinkstudio.2026@gmail.com">artinkstudio.2026@gmail.com</a><a href="tel:+38970283590">+389 70 283 590</a><a href="https://wa.me/38970283590" rel="noopener" target="_blank">WhatsApp</a><a href="https://www.instagram.com/artinkstudio.mk/" rel="noopener" target="_blank">Instagram ↗</a></div><div class="footer-links"><a href="${url(lang,'/products/')}">${t[lang].navProducts}</a><a href="${url(lang,'/catalog/')}">${t[lang].navCatalog}</a><a href="${url(lang,'/privacy/')}">${t[lang].privacy}</a><a href="${url(lang,'/contact/')}">${t[lang].navContact}</a></div></div><div class="container-fluid page-width footer-bottom"><span>© ${new Date().getUTCFullYear()} ArtInk Studio</span><span>Skopje · North Macedonia</span></div></footer><aside id="privacy-notice" class="privacy-notice" role="dialog" aria-label="${t[lang].privacy}" hidden><div><strong>${t[lang].privacy}</strong><p>${t[lang].privacyIntro} <a href="${url(lang,'/privacy/')}">${t[lang].privacy} ↗</a></p></div><button id="privacy-accept" type="button">${t[lang].accept}</button></aside>`;
const page = (lang, title, description, content, suffix, active='') => {
  const canonical = `${origin}${url(lang,suffix)}`;
  const alternate = ['en','mk','sq'].map(l=>`<link rel="alternate" hreflang="${l==='sq'?'sq':l}" href="${origin}${url(l,suffix)}">`).join('');
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · ArtInk Studio</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#0d1725"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)} · ArtInk Studio"><meta property="og:description" content="${escape(description)}"><meta property="og:image" content="${origin}/images/hero.webp"><link rel="canonical" href="${canonical}">${alternate}<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://cdn.jsdelivr.net"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/product.css"><link rel="stylesheet" href="/refresh.css"><script src="/site.js" defer></script></head><body>${nav(lang,active)}${content}${footer(lang)}</body></html>`;
};
const card = (p,lang) => `<a class="product-card" data-category="${p.category}" data-search="${escape([p.name_en,p.name_mk,p.name_sq,p.short_en,p.short_mk,p.short_sq,p.code].join(' ').toLocaleLowerCase())}" href="${url(lang,`/product/${p.slug}/`)}"><div class="card-image"><img src="${escape(p.images[0])}" alt="${escape(p[`name_${lang}`])}" loading="lazy"><span class="image-arrow">↗</span></div><div class="card-copy"><span class="eyebrow">${escape(cat[lang][categories.indexOf(p.category)])}</span><h3>${escape(p[`name_${lang}`])}</h3><p>${escape(p[`short_${lang}`])}</p><span class="card-link">${t[lang].view} <span>↗</span></span></div></a>`;
const home = lang => `<main>${slides(lang,{t,url})}<div class="marquee" aria-hidden="true"><div>${Array(4).fill(`<span>${t[lang].strip}</span><b>✳</b>`).join('')}</div></div><section class="section section-featured container-fluid page-width"><div class="section-head"><div><span class="eyebrow gold">01 / ${t[lang].featured}</span><h2>${t[lang].title}</h2></div><a class="text-link" href="${url(lang,'/products/')}">${t[lang].browse} ↗</a></div><div class="product-grid featured-grid">${products.filter(p=>p.featured).slice(0,4).map(p=>card(p,lang)).join('')}</div><p class="photo-note">${t[lang].photoNote}</p></section><section id="about" class="about-section"><div class="container-fluid page-width about-grid"><div class="about-visual"><img src="/images/hero.webp" loading="lazy" alt="Personalised apparel, mug, cap and invitation"><span>PRINT / PERSONALISE / KEEP</span></div><div class="about-copy"><span class="eyebrow gold">${t[lang].aboutKicker}</span><h2>${t[lang].aboutTitle}</h2><p>${t[lang].aboutText}</p><a class="text-link" href="${url(lang,'/products/')}">${t[lang].browse} ↗</a></div></div></section><section class="contact-section"><div class="container-fluid page-width contact-grid"><div><span class="eyebrow gold">02 / ${t[lang].navContact}</span><h2>${t[lang].contactTitle}</h2><p>${t[lang].contactText}</p><a class="button button-gold" href="${url(lang,'/contact/')}">${t[lang].sendInquiry} ↗</a></div><div class="contact-links"><a href="${url(lang,'/contact/')}">${t[lang].navContact}<span>↗</span></a><a href="https://wa.me/38970283590" target="_blank" rel="noopener">WhatsApp<span>↗</span></a><a href="https://www.instagram.com/artinkstudio.mk/" target="_blank" rel="noopener">Instagram<span>↗</span></a></div></div></section></main>`;
const catalog = lang => `<main class="catalog-main container-fluid page-width"><div class="catalog-top"><span class="eyebrow gold">ARTINK / ${t[lang].navProducts}</span><h1>${t[lang].title}</h1><p>${t[lang].catalogText}</p></div><div class="catalog-controls"><label class="search-box"><span aria-hidden="true">⌕</span><input id="product-search" type="search" placeholder="${t[lang].search}" aria-label="${t[lang].search}"></label><div class="filters" aria-label="Categories"><button type="button" class="filter is-selected" data-filter="all" aria-pressed="true">${t[lang].all}</button>${categories.map((c,i)=>`<button type="button" class="filter" data-filter="${c}" aria-pressed="false">${cat[lang][i]}</button>`).join('')}</div></div><div class="product-grid catalog-grid" id="catalog-grid">${products.map(p=>card(p,lang)).join('')}</div><p id="empty-state" class="empty-state" hidden>${t[lang].noResults}</p><p class="photo-note">${t[lang].photoNote}</p></main>`;
const detail = (p,lang) => productDetail(p,lang,{t,cat,categories,products,escape,url,card});
const lookbook = (lang,config) => digitalCatalog(lang,{t,cat,categories,products,escape,url,config});
const privacyText = {
 en:['ArtInk Studio, Skopje, North Macedonia, operates this catalogue. For privacy questions contact artinkstudio.2026@gmail.com.','When you submit our inquiry form, Netlify processes the submitted name, email, optional phone number, product, colour, size, quantity and message, and forwards the inquiry to us. We use the details to answer you and prepare a quote. Email and WhatsApp links open their respective applications; messages sent there are handled by those providers.','The notice choice is stored in your browser’s local storage. We do not run analytics or advertising cookies on this version of the website. The website loads Bootstrap, Google Fonts and the admin editor from external providers; your browser may contact those providers. The catalogue may include externally hosted example images.','Only authorised editors access the product editor. It uses GitHub authentication and stores product content and uploaded media in the site repository. Do not enter customer personal information in public product descriptions.','You may ask us to access, correct or delete the personal details you sent us by emailing artinkstudio.2026@gmail.com. We keep quote correspondence only as long as needed for communication, orders and applicable record obligations. This notice may be updated when new features are added.'],
 mk:['ArtInk Studio, Скопје, Северна Македонија, го води овој каталог. За прашања за приватност пишете на artinkstudio.2026@gmail.com.','Кога ја испраќате контакт-формата, Netlify ги обработува името, е-поштата, незадолжителниот телефон, производот, бојата, големината, количината и пораката, и го проследува барањето до нас. Ги користиме податоците за одговор и подготовка на понуда. Линковите за е-пошта и WhatsApp отвораат други апликации и пораките таму ги обработуваат нивните даватели.','Изборот за известувањето се чува во локалното складирање на вашиот прелистувач. Во оваа верзија нема аналитички или рекламни колачиња. Страницата вчитува Bootstrap, Google Fonts и административен editor од надворешни добавувачи; прелистувачот може да се поврзе со нив. Некои примерни слики може да се вчитуваат од надворешен извор.','Само овластени уредници пристапуваат до панелот. Тој користи GitHub најавување и ги чува производите и поставените слики во репозиториумот. Не внесувајте лични податоци на клиенти во јавни описи.','Може да побарате пристап, исправка или бришење на личните податоци што сте ни ги испратиле на artinkstudio.2026@gmail.com. Кореспонденцијата ја чуваме колку што е потребно за комуникација, нарачки и применливи обврски. Известувањето ќе го ажурираме при додавање нови функции.'],
 sq:['ArtInk Studio, Shkup, Maqedonia e Veriut, administron këtë katalog. Për pyetje mbi privatësinë, shkruani në artinkstudio.2026@gmail.com.','Kur dërgoni formularin e kontaktit, Netlify përpunon emrin, emailin, telefonin opsional, produktin, ngjyrën, madhësinë, sasinë dhe mesazhin, dhe na përcjell kërkesën. I përdorim të dhënat për t’ju përgjigjur dhe për të përgatitur ofertën. Lidhjet e emailit dhe WhatsApp hapin aplikacione të tjera, ku mesazhet përpunohen nga ofruesit e tyre.','Zgjedhja për njoftimin ruhet në hapësirën lokale të shfletuesit. Kjo faqe nuk përdor cookies për analiza ose reklama. Faqja ngarkon Bootstrap, Google Fonts dhe editorin administrativ nga ofrues të jashtëm; shfletuesi mund të lidhet me ta. Disa foto shembull mund të vijnë nga burime të jashtme.','Vetëm redaktorët e autorizuar hyjnë në panel. Ai përdor identifikim përmes GitHub dhe ruan përmbajtjen e produkteve dhe fotot në repository. Mos vendosni të dhëna personale të klientëve në përshkrimet publike.','Mund të kërkoni qasje, korrigjim ose fshirje të të dhënave personale që na keni dërguar duke shkruar në artinkstudio.2026@gmail.com. Korrespondencën e mbajmë vetëm aq sa nevojitet për komunikim, porosi dhe detyrime të zbatueshme. Njoftimi do të përditësohet kur të shtohen funksione të reja.']
};
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true}); await cp(path.join(root,'static'),out,{recursive:true});
const write = async (suffix,html) => {const dest=path.join(out,suffix); await mkdir(path.dirname(dest),{recursive:true}); await writeFile(dest,html)};
const config = JSON.parse(await readFile(path.join(root, 'content/catalog.json'), 'utf8'));
const locs=[];
for (const lang of ['en','mk','sq']) {
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}index.html`,page(lang,t[lang].heroTitle,t[lang].heroText,home(lang),'','home')); locs.push(url(lang));
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}products/index.html`,page(lang,t[lang].navProducts,t[lang].catalogText,catalog(lang),'/products/','products')); locs.push(url(lang,'/products/'));
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}contact/index.html`,page(lang,t[lang].navContact,t[lang].contactText,contactPage(lang,{t,url,escape}),'/contact/','contact'));locs.push(url(lang,'/contact/'));
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}contact/sent/index.html`,page(lang,t[lang].sentTitle,t[lang].sentText,thankYou(lang,{t,url}),'/contact/sent/','sent'));locs.push(url(lang,'/contact/sent/'));
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}catalog/index.html`,page(lang,t[lang].navCatalog,config[`intro_${lang}`] || t[lang].lookbookIntro,lookbook(lang,config),'/catalog/','lookbook')); locs.push(url(lang,'/catalog/'));
  for (const p of products) {await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}product/${p.slug}/index.html`,page(lang,p[`name_${lang}`],p[`short_${lang}`],detail(p,lang),`/product/${p.slug}/`,`product:${p.slug}`));locs.push(url(lang,`/product/${p.slug}/`));}
  await write(`${base(lang).slice(1)}${lang==='en'?'':'/'}privacy/index.html`,page(lang,t[lang].privacy,t[lang].privacyIntro,`<main class="policy-main container-fluid page-width"><span class="eyebrow gold">ARTINK / PRIVACY</span><h1>${t[lang].privacy}</h1><div class="policy-body">${privacyText[lang].map(x=>`<p>${escape(x)}</p>`).join('')}</div></main>`,'/privacy/','privacy'));locs.push(url(lang,'/privacy/'));
}
await writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${locs.map(l=>`<url><loc>${origin}${l}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${locs.length} pages for ${products.length} products.`);
