export function slides(lang, { t, url }) {
  const copy = t[lang];
  const panels = [
    { image: '/images/hero.webp', eyebrow: copy.heroEyebrow, title: copy.heroTitle, text: copy.heroText, destination: '/products/', label: copy.browse },
    { image: '/images/tshirt.webp', eyebrow: copy.slideClothesTag, title: copy.slideClothesTitle, text: copy.slideClothesText, destination: '/products/?category=tshirts', label: copy.browse },
    { image: '/images/invitation.webp', eyebrow: copy.slideMomentsTag, title: copy.slideMomentsTitle, text: copy.slideMomentsText, destination: '/contact/', label: copy.talk }
  ];
  return `<section class="hero hero-carousel" aria-label="${copy.slidesLabel}" aria-roledescription="carousel" id="home-slides">${panels.map((p, i) => `<div class="hero-panel ${i === 0 ? 'is-current' : ''}" data-slide="${i}" aria-hidden="${i !== 0}"><div class="hero-media" style="background-image:linear-gradient(90deg,#0d1725 0%,#0d1725e8 34%,#0d172588 63%,#0d17254d 100%),url('${p.image}')" aria-hidden="true"></div><div class="container-fluid page-width hero-inner"><div class="hero-copy"><span class="eyebrow gold">${p.eyebrow}</span><h1>${p.title}</h1><p>${p.text}</p><div class="hero-buttons"><a class="button button-gold" href="${url(lang, p.destination)}" ${i ? 'tabindex="-1"' : ''}>${p.label} <span>↗</span></a><a class="button button-ghost" href="${url(lang, '/contact/')}" ${i ? 'tabindex="-1"' : ''}>${copy.navContact}</a></div></div></div></div>`).join('')}<div class="container-fluid page-width carousel-controls"><div class="slide-dots" aria-label="${copy.slidesLabel}">${panels.map((_, i) => `<button type="button" class="slide-dot ${i === 0 ? 'is-current' : ''}" data-slide-to="${i}" aria-label="${copy.slideLabel} ${i + 1}" aria-current="${i === 0 ? 'true' : 'false'}"></button>`).join('')}</div><div class="slide-arrows"><button type="button" data-slide-direction="-1" aria-label="${copy.previousSlide}">←</button><button type="button" data-slide-direction="1" aria-label="${copy.nextSlide}">→</button></div><span class="slide-count" aria-live="polite">01 / 03</span></div></section>`;
}

export function contactPage(lang, { t, url, escape }) {
  const c = t[lang];
  const field = (key, type, required = false, extra = '') => `<label class="form-field"><span>${c[key]}${required ? ' *' : ''}</span><input ${extra} type="${type}" name="${key}" id="inquiry-${key}" ${required ? 'required' : ''}></label>`;
  const contactOptions = `<div class="contact-options"><a href="mailto:artinkstudio.2026@gmail.com">${c.email} ↗</a><a href="https://wa.me/38970283590" target="_blank" rel="noopener">WhatsApp ↗</a><a href="tel:+38970283590">${c.call} ↗</a><a href="https://www.instagram.com/artinkstudio.mk/" target="_blank" rel="noopener">Instagram ↗</a></div>`;
  return `<main class="inquiry-main container-fluid page-width"><div class="inquiry-head"><span class="eyebrow gold">ARTINK / ${c.navContact}</span><h1>${c.contactTitle}</h1><p>${c.contactText}</p></div><div class="inquiry-grid"><div class="inquiry-card"><div class="inquiry-card-header"><span>01 / ${c.inquiryTag}</span><h2>${c.inquiryTitle}</h2><p>${c.inquiryHint}</p></div><form name="artink-inquiry" method="POST" data-netlify="true" netlify-honeypot="website" action="${url(lang, '/contact/sent/')}" id="inquiry-form"><input type="hidden" name="form-name" value="artink-inquiry"><input type="hidden" name="source" value="${lang}"><div class="honey-field" aria-hidden="true"><label>Do not fill this field <input name="website" type="text" tabindex="-1" autocomplete="off"></label></div><div class="form-row">${field('yourName', 'text', true, 'autocomplete="name"')}${field('yourEmail', 'email', true, 'autocomplete="email"')}</div><div class="form-row">${field('yourPhone', 'tel', false, 'autocomplete="tel"')}${field('requestedQuantity', 'number', false, 'min="1" step="1" inputmode="numeric"')}</div>${field('productName', 'text')}<div class="form-row">${field('colour', 'text')}${field('size', 'text')}</div><label class="form-field"><span>${c.message} *</span><textarea id="inquiry-message" name="message" rows="6" required placeholder="${escape(c.messagePlaceholder)}"></textarea></label><p class="form-privacy">${c.formPrivacy} <a href="${url(lang, '/privacy/')}">${c.privacy} ↗</a></p><button class="button button-gold form-submit" type="submit">${c.sendInquiry} <span>↗</span></button><p class="local-submit-note" id="local-submit-note" hidden role="status">${c.localFormNote}</p></form></div><aside class="inquiry-aside"><span class="eyebrow gold">02 / ${c.otherContact}</span><h2>${c.otherContactTitle}</h2><p>${c.otherContactText}</p>${contactOptions}<div class="inquiry-aside-art" aria-hidden="true"><span>ARTINK</span><small>MADE FOR YOU ↗</small></div></aside></div></main>`;
}

export function thankYou(lang, { t, url }) {
  const c = t[lang];
  return `<main class="sent-main container-fluid page-width"><span class="sent-symbol" aria-hidden="true">✳</span><span class="eyebrow gold">ARTINK / ${c.navContact}</span><h1>${c.sentTitle}</h1><p>${c.sentText}</p><a class="button button-gold" href="${url(lang, '/products/')}">${c.browse} ↗</a></main>`;
}
