export function productDetail(p, lang, { t, cat, categories, products, escape, url, card }) {
  const copy = t[lang];
  const name = p[`name_${lang}`];
  const groupName = cat[lang][categories.indexOf(p.category)];
  const related = products.filter(other => other.slug !== p.slug && (
    p.collection && other.collection === p.collection || other.category === p.category
  )).sort((a, b) => Number(Boolean(b.collection && b.collection === p.collection)) - Number(Boolean(a.collection && a.collection === p.collection))).slice(0, 3);
  const details = [
    [copy.code, p.code], [copy.model, p.model], [copy.brand, p.brand],
    [copy.material, p[`material_${lang}`] || p.material], [copy.weight, p.weight],
    [copy.packaging, p.packaging], [copy.collection, p.collection]
  ].filter(([,value]) => value);
  const colors = Array.isArray(p.colors) ? p.colors.filter(c => c && c.name && /^#[0-9a-fA-F]{6}$/.test(c.hex)) : [];
  const sizes = Array.isArray(p.sizes) ? p.sizes : [];
  const stock = Array.isArray(p.stock) ? p.stock : [];
  const selectionData = escape(JSON.stringify({
    subject: `${copy.subject}: ${name}`,
    product: name, code: p.code || '', language: lang,
    body: `${copy.body}${name}${p.code ? ' (' + p.code + ')' : ''}\n`,
    stock, inStock: copy.inStock, outOfStock: copy.outOfStock,
    askStock: copy.askStock, selectedColor: copy.selectedColor,
    selectedSize: copy.selectedSize, quantityLabel: copy.quantityLabel,
    contactPath: url(lang, '/contact/')
  }));
  const gallery = `<div class="detail-images"><div class="detail-primary"><img id="detail-image" src="${escape(p.images[0])}" alt="${escape(name)}"></div><div class="thumbs" aria-label="${copy.gallery}">${p.images.map((im,i)=>`<button type="button" class="thumb ${i===0?'is-selected':''}" data-image="${escape(im)}" aria-label="${copy.image} ${i+1}" aria-pressed="${i===0}"><img src="${escape(im)}" alt="" loading="lazy"></button>`).join('')}</div></div>`;
  return `<main class="detail-main container-fluid page-width"><a class="back-link" href="${url(lang,'/products/')}">← ${copy.back}</a><div class="detail-grid">${gallery}<div class="detail-copy" id="product-selection" data-product="${selectionData}"><a class="group-link" href="${url(lang,`/products/?category=${p.category}`)}">${escape(groupName)} ↗</a><h1>${escape(name)}</h1><p class="detail-lead">${escape(p[`short_${lang}`])}</p><p class="detail-description">${escape(p[`description_${lang}`])}</p>${colors.length ? `<div class="variant-block"><h2>${copy.colors}</h2><div class="swatch-list">${colors.map(c=>`<button type="button" class="swatch-option" data-color="${escape(c.name)}" aria-pressed="false" title="${escape(c[`name_${lang}`] || c.name)}"><span class="swatch-dot" style="background-color:${escape(c.hex)}"></span><span>${escape(c[`name_${lang}`] || c.name)}</span></button>`).join('')}</div></div>` : ''}${sizes.length ? `<div class="variant-block"><h2>${copy.sizes}</h2><div class="size-list">${sizes.map(s=>`<button type="button" class="size-option" data-size="${escape(s)}" aria-pressed="false">${escape(s)}</button>`).join('')}</div></div>` : ''}<div class="variant-block quantity-block"><label for="requested-quantity">${copy.quantityLabel}</label><input id="requested-quantity" type="number" min="1" step="1" inputmode="numeric" value="1" aria-label="${copy.quantityLabel}"><p>${copy.quantityNote}</p></div><p id="stock-message" class="stock-message" aria-live="polite">${copy.askStock}</p>${details.length ? `<dl class="detail-attributes">${details.map(([label,value])=>`<div><dt>${label}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl>` : ''}${p.options ? `<p class="additional-options"><strong>${copy.options}:</strong> ${escape(p.options)}</p>` : ''}<div class="quote-actions"><a id="quote-form-link" class="button button-gold detail-quote" href="${url(lang,'/contact/')}">${copy.quoteForm} <span>↗</span></a><a id="quote-link" class="button button-outline" href="mailto:artinkstudio.2026@gmail.com?subject=${encodeURIComponent(`${copy.subject}: ${name}`)}">${copy.quoteEmail} ↗</a><a id="quote-whatsapp" class="button button-outline" href="https://wa.me/38970283590" target="_blank" rel="noopener">${copy.quoteWhatsapp} ↗</a></div><p class="availability">${copy.availability}</p></div></div>${related.length ? `<section class="related-section"><div class="section-head"><div><span class="eyebrow gold">${copy.discoverMore}</span><h2>${copy.related}</h2></div><a class="text-link" href="${url(lang,`/products/?category=${p.category}`)}">${copy.viewGroup} ↗</a></div><div class="product-grid">${related.map(item=>card(item,lang)).join('')}</div></section>` : ''}<p class="photo-note">${copy.photoNote}</p></main>`;
}

export function digitalCatalog(lang, { t, cat, categories, products, escape, url, config }) {
  const copy = t[lang];
  const featuredGroups = categories.filter(category => products.some(p => p.category === category));
  const file = config.pdf_file && String(config.pdf_file).startsWith('/') ? config.pdf_file : '';
  return `<main class="lookbook-main"><section class="lookbook-intro container-fluid page-width"><div><span class="eyebrow gold">ARTINK / ${copy.navCatalog}</span><h1>${escape(config[`title_${lang}`] || copy.lookbookTitle)}</h1><p>${escape(config[`intro_${lang}`] || copy.lookbookIntro)}</p><div class="lookbook-actions"><a class="button button-gold" href="#chapters">${copy.browseChapters} ↗</a>${file ? `<a class="button button-outline" href="${escape(file)}" target="_blank" rel="noopener">${copy.openPdf} ↗</a>` : ''}</div></div><div class="lookbook-cover"><img src="${escape(config.cover_image || '/images/hero.webp')}" alt="${copy.catalogCover}"><span>ARTINK STUDIO / ${new Date().getUTCFullYear()}</span></div></section><section id="chapters" class="lookbook-chapters container-fluid page-width"><div class="section-head"><div><span class="eyebrow gold">01 / ${copy.chapters}</span><h2>${copy.exploreCollection}</h2></div><span class="chapter-count">${String(featuredGroups.length).padStart(2,'0')} ${copy.chapters}</span></div><div class="chapter-grid">${featuredGroups.map((category,i)=>{const items=products.filter(p=>p.category===category);return `<a class="chapter" href="${url(lang,`/products/?category=${category}`)}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><img src="${escape(items[0].images[0])}" alt="${escape(cat[lang][categories.indexOf(category)])}" loading="lazy"><div><h3>${escape(cat[lang][categories.indexOf(category)])}</h3><span>${items.length} ${copy.items} ↗</span></div></a>`}).join('')}</div></section>${file ? `<section class="catalog-pdf container-fluid page-width"><div class="section-head"><div><span class="eyebrow gold">02 / PDF</span><h2>${copy.pdfCatalog}</h2></div><a class="text-link" href="${escape(file)}" target="_blank" rel="noopener">${copy.openPdf} ↗</a></div><object data="${escape(file)}" type="application/pdf" aria-label="${copy.pdfCatalog}"><p><a href="${escape(file)}">${copy.openPdf}</a></p></object></section>` : ''}</main>`;
}
